#ifndef SPRITES_PATH_H
#define SPRITES_PATH_H

#include "../common/enums.h"
#include <map>
#include <string>

const std::map<enum AnimationState, std::string> sprites_path = {
    // JAZZ
    {IDLE_JAZZ, "/jazz_sprites/idle_jazz.png"},
    {WALKING_JAZZ, "/jazz_sprites/walking_jazz.png"},
    {RUNNING_JAZZ, "/jazz_sprites/running_jazz.png"},
    {PREPARING_TO_DASH_JAZZ, "/jazz_sprites/dashing/preparing_to_dash_jazz.png"},
    {DASHING_JAZZ, "/jazz_sprites/dashing/dashing_jazz.png"},
    {SKIDDING_JAZZ, "/jazz_sprites/dashing/skidding_jazz.png"},
    {TRANSITION_TO_JUMPING_JAZZ, "/jazz_sprites/jumping_up/transition_to_jumping_jazz.png"},
    {JUMPING_UP_JAZZ, "/jazz_sprites/jumping_up/jumping_up_jazz.png"},
    {TRANSITION_TO_FALLING_JAZZ, "/jazz_sprites/jumping_up/jumping_up_jazz.png"},
    {FALLING_JAZZ, "/jazz_sprites/falling_jazz.png"},
    {LANDING_JAZZ, "/jazz_sprites/landing_jazz.png"},
    {JUMPING_FORWARD_JAZZ, "/jazz_sprites/jumping_foward/jumping_foward_jazz.png"},
    {FALLING_FORWARD_JAZZ, "/jazz_sprites/jumping_foward/falling_foward_jazz.png"},
    {SHOOTING_WHILE_FALLING_JAZZ, "/jazz_sprites/shooting_while_falling_jazz.png"},
    {STOP_SHOOTING_WHILE_FALLING_JAZZ, "/jazz_sprites/stop_shooting_while_falling_jazz.png"},
    {SHOOTING_JAZZ, "/jazz_sprites/shooting_jazz.png"},
    {STOP_SHOOTING_JAZZ, "/jazz_sprites/stop_shooting_jazz.png"},
    {LOOKING_UP_JAZZ, "/jazz_sprites/looking_up_jazz.png"},
    {SHOOTING_UP_JAZZ, "/jazz_sprites/shooting_up_jazz.png"},
    {CROUCHING_JAZZ, "/jazz_sprites/crouching/crouching_jazz.png"},
    {CROUCH_JAZZ, "/jazz_sprites/crouching/crouch_jazz.png"},
    {CROUCH_SHOOTING_JAZZ, "/jazz_sprites/crouching/crouching_shooting_jazz.png"},
    {STANDING_UP_JAZZ, "/jazz_sprites/crouching/standing_up_jazz.png"},
    {TRANSITION_TO_UPPERCUT_JAZZ, "/jazz_sprites/uppercut/transition_to_uppercut_jazz.png"},
    {UPPERCUT_JAZZ, "/jazz_sprites/uppercut/uppercut.png"},
    {TRANSITION_TO_FALLING_AFTER_UPPERCUT_JAZZ, "/jazz_sprites/uppercut/transition_to_falling_after_uppercut_jazz.png"},
    {INTOXICATED_IDLE_JAZZ, "/jazz_sprites/intoxicated/intoxicated_idle_jazz.png"},
    {INTOXICATED_WALKING_JAZZ, "/jazz_sprites/intoxicated/intoxicated_walking_jazz.png"},
    {RECEIVE_DAMAGE_JAZZ, "/jazz_sprites/receive_damage_jazz.png"},
    {IMPACT_JAZZ, "/jazz_sprites/impact_jazz.png"},
    {DYING_JAZZ, "/jazz_sprites/dying_jazz.png"},
    // LORI
    {IDLE_LORI, "/lori_sprites/idle_lori.png"},
    {WALKING_LORI, "/lori_sprites/walking_lori.png"},
    {RUNNING_LORI, "/lori_sprites/running_lori.png"},
    {PREPARING_TO_DASH_LORI, "/lori_sprites/dashing/preparing_to_dash_lori.png"},
    {DASHING_LORI, "/lori_sprites/dashing/dashing_lori.png"},
    {SKIDDING_LORI, "/lori_sprites/dashing/skidding_lori.png"},
    {TRANSITION_TO_JUMPING_LORI, "/lori_sprites/jumping_up/transition_to_jumping_lori.png"},
    {JUMPING_UP_LORI, "/lori_sprites/jumping_up/jumping_up_lori.png"},
    {TRANSITION_TO_FALLING_LORI, "/lori_sprites/jumping_up/jumping_up_lori.png"},
    {FALLING_LORI, "/lori_sprites/falling_lori.png"},
    {LANDING_LORI, "/lori_sprites/landing_lori.png"},
    {JUMPING_FORWARD_LORI, "/lori_sprites/jumping_foward/jumping_foward_lori.png"},
    {FALLING_FORWARD_LORI, "/lori_sprites/jumping_foward/falling_foward_lori.png"},
    {SHOOTING_WHILE_FALLING_LORI, "/lori_sprites/shooting_while_falling_lori.png"},
    {STOP_SHOOTING_WHILE_FALLING_LORI, "/lori_sprites/stop_shooting_while_falling_lori.png"},
    {SHOOTING_FORWARD_LORI, "/lori_sprites/shooting_forward_lori.png"},
    {STOP_SHOOTING_FORWARD_LORI, "/lori_sprites/stop_shooting_forward_lori.png"},
    {LOOKING_UP_LORI, "/lori_sprites/looking_up_lori.png"},
    {SHOOTING_UP_LORI, "/lori_sprites/shooting_up_lori.png"},
    {CROUCHING_LORI, "/lori_sprites/crouching/crouching_lori.png"},
    {CROUCH_LORI, "/lori_sprites/crouching/crouch_lori.png"},
    {CROUCH_SHOOTING_LORI, "/lori_sprites/crouching/crouching_shooting_lori.png"},
    {STANDING_UP_LORI, "/lori_sprites/crouching/standing_up_lori.png"},
    {FLYING_KICK_LORI, "/lori_sprites/flying_kick_lori.png"},
    {INTOXICATED_IDLE_LORI, "/lori_sprites/intoxicated/intoxicated_idle_lori.png"},
    {INTOXICATED_WALKING_LORI, "/lori_sprites/intoxicated/intoxicated_walking_lori.png"},
    //{RECEIVE_DAMAGE_LORI, "/lori_sprites/recive_damage_lori.png"},
    {RECEIVE_DAMAGE_LORI, "/lori_sprites/receive_damage_lori.png"},
    //{DYING_LORI,"/lori_sprites/dying_lori.png"}, sprite no existe

    // SPAZ
    {IDLE_SPAZ, "/spaz_sprites/idle_spaz.png"},
    {WALKING_SPAZ, "/spaz_sprites/walking_spaz.png"},
    {RUNNING_SPAZ, "/spaz_sprites/running_spaz.png"},
    {PREPARING_TO_DASH_SPAZ, "/spaz_sprites/preparing_to_dash_spaz.png"},
    {DASHING_SPAZ, "/spaz_sprites/dashing_spaz.png"},
    {SKIDDING_SPAZ, "/spaz_sprites/skidding_spaz.png"},
    {STOP_SKIDDING_SPAZ, "/spaz_sprites/stop_skidding_spaz.png"},
    {TRANSITION_TO_JUMPING_SPAZ, "/spaz_sprites/transition_to_jumping_spaz.png"},
    {JUMPING_UP_SPAZ, "/spaz_sprites/jumping_up_spaz.png"},
    {TRANSITION_TO_FALLING_SPAZ, "/spaz_sprites/jumping_up_spaz.png"},
    {FALLING_SPAZ, "/spaz_sprites/falling_spaz.png"},
    {LANDING_SPAZ, "/spaz_sprites/landing_spaz.png"},
    {JUMPING_FORWARD_SPAZ, "/spaz_sprites/jumping_forward_spaz.png"},
    {FALLING_FORWARD_SPAZ, "/spaz_sprites/falling_forward_lori.png"},
    {SHOOTING_WHILE_FALLING_SPAZ, "/spaz_sprites/shooting_while_falling_spaz.png"},
    {STOP_SHOOTING_WHILE_FALLING_SPAZ, "/spaz_sprites/stop_shooting_while_falling_spaz.png"},
    {SHOOTING_FORWARD_SPAZ, "/spaz_sprites/shooting_forward_spaz.png"},
    {STOP_SHOOTING_FORWARD_SPAZ, "/spaz_sprites/stop_shooting_forward_spaz.png"},
    {LOOKING_UP_SPAZ, "/spaz_sprites/looking_up_spaz.png"},
    {SHOOTING_UP_SPAZ, "/spaz_sprites/shooting_up_spaz.png"},
    {CROUCHING_SPAZ, "/spaz_sprites/crouching_spaz.png"},
    {CROUCH_SPAZ, "/spaz_sprites/crouch_spaz.png"},
    {CROUCH_SHOOTING_SPAZ, "/spaz_sprites/crouching_shooting_spaz.png"},
    {STANDING_UP_SPAZ, "/spaz_sprites/standing_up_spaz.png"},
    {TRANSITION_TO_FLYING_KICK_SPAZ, "/spaz_sprites/transition_to_flying_kick_spaz.png"},
    {FLYING_KICK_SPAZ, "/spaz_sprites/flying_kick_spaz.png"},
    {TRANSITION_AFTER_KICK_SPAZ, "/spaz_sprites/transition_after_kick_spaz.png"},
    {INTOXICATED_IDLE_SPAZ, "/spaz_sprites/intoxicated_idle_spaz.png"},
    {INTOXICATED_WALKING_SPAZ, "/spaz_sprites/intoxicated_walking_spaz.png"},
    {RECEIVE_DAMAGE_SPAZ, "/spaz_sprites/receive_damage_spaz.png"},

    // ENEMIES
    {WALKING_LIZARD, "/enemies_sprites/walking_lizard.png"},
    {FLYING_BAT, "/enemies_sprites/bat.png"},
    {WALKING_SKELETON, "/enemies_sprites/skeleton.png"},
    {CRAB, "/beachLevel/crab.png"},
    {FISH, "/beachLevel/fish.png"},
    {TURTLE, "/beachLevel/turtle.png"},

    // ITEMS
    {GEM, "/items_sprites/gem.png"},
    {COIN, "/items_sprites/coin.png"},
    {POISON_FRUIT, "/items_sprites/poison.png"},
    // AMMO
    {FIREBALL, "/items_sprites/ammo/fireball.png"},
    {SHOT_FIREBALL, "/items_sprites/ammo/shot_fireball.png"},

    {RED_ROCKET, "/items_sprites/ammo/red_rocket.png"},
    {SHOT_RED_ROCKET, "/items_sprites/ammo/shot_red_rocket.png"},

    {BULLET, "/items_sprites/ammo/bullet.png"},

    // Escenario
    {Background_AIW, "/SceneryAIW/background.png"},
    {Background2, ""},
    {EMPTY_BACKGROUND, "/empty_background.jpg"},
    {Background_BEACH, "/beachLevel/background.png"},

    // Beach level
    {BEACH_FLOOR, "/beachLevel/floor.png"},
    {BEACH_FLOATING_FLOOR, "/beachLevel/floating_floor.png"},
    {BEACH_PLATFORM, "/beachLevel/platform.png"},
    {BEACH_FLOATING_PLATFORM, "/beachLevel/floating_platform.png"},
    {BEACH_RISE, "/beachLevel/stairs_up.png"},
    {BEACH_DESCENT, "/beachLevel/stairs_down.png"},
    {BEACH_RISE_DESCENT, "/beachLevel/rise_descent.png"},
    {BEACH_EXIT_SIGN, "/beachLevel/exit.png"},
    {BEACH_LANDSCAPE, "/beachLevel/landscape.png"},
    {BEACH_FLOATING_PLATFORM, "/beachLevel/floating_platform.png"},
    {BEACH_RISE, "/beachLevel/stairs_up.png"},
    {BEACH_DESCENT, "/beachLevel/stairs_down.png"},
    {BEACH_ALGAE, "/beachLevel/algae.png"},

    {DYING_INVISIBLE, "/empty_background.jpg"},
    // Editor
    {SPAWN_POINT, "/spawnPoint.png"},

    {ARROW, "/SceneryAIW/arrow_right.png"},
    {FLOOR_AIW, "/SceneryAIW/floor4.png"},
    {GUITAR, "/SceneryAIW/guitar.png"},
    {CHESIRE, "/SceneryAIW/cheshire.png"},
    {DESCENT, "/SceneryAIW/descent.png"},
    {RISE, "/SceneryAIW/rise.png"},
    {RED_MUSHROOM, "/SceneryAIW/red_mushrooms.png"},
    {EXIT, "/SceneryAIW/exit.png"},
    {ROCKS, "/SceneryAIW/rocks3.png"},
    {ROCKS3_AIW, "/SceneryAIW/rocks4.png"},
    {ROCKS2_AIW, "/SceneryAIW/rocks.png"},
    {FLOOR2_AIW, "/SceneryAIW/floor2.png"},
    {FLOOR3_AIW, "/SceneryAIW/floor6.png"},
    {FLOOR4_AIW, "/SceneryAIW/floor7.png"},
    {COLUMN_STONES, "/SceneryAIW/columnStones.png"},
    {COLUMN_STONES_RIGHT, "/SceneryAIW/columnStonesRight.png"},
    {STONE_TOWER, "/SceneryAIW/stoneTower.png"},
    {COLUMN_STONES_LOWER, "/SceneryAIW/columnStoneLower.png"},
    {COLUMN_STONES_LOWER_RIGHT, "/SceneryAIW/columnStoneLowerRight.png"},
    {FLOOR_AFTER_RAISE, "/SceneryAIW/afterRise.png"},
    {ROCKS_AFTER_RAISE, "/SceneryAIW/afterRiseRock.png"},
    {FLOOR_BEFORE_DESCENT, "/SceneryAIW/beforeDescent.png"},
    {ROCKS_BEFORE_DESCENT, "/SceneryAIW/beforeRiseRock.png"},
    {FLOOR_STONE_TOWER, "/SceneryAIW/floorStoneTower.png"},
    // Enemies
    {MAD_HATTER, "/SceneryAIW/mad_hatter.png"},
    {SKELETON, "/SceneryAIW/skeleton.png"},
    {DYING_LORI, "/lori_sprites/dying_lori.png"},
    {DYING_SPAZ, "/spaz_sprites/dying_spaz.png"},

};

#endif
