#ifndef ENUMS_H
#define ENUMS_H

#include <cstdint>

enum AnimationState : uint8_t
{
    IDLE_JAZZ = 0x00,
    WALKING_JAZZ,
    RUNNING_JAZZ,
    JUMPING_JAZZ,
    PREPARING_TO_DASH_JAZZ,
    DASHING_JAZZ,
    SKIDDING_JAZZ,
    TRANSITION_TO_JUMPING_JAZZ,
    JUMPING_UP_JAZZ,
    TRANSITION_TO_FALLING_JAZZ,
    FALLING_JAZZ, // 10
    LANDING_JAZZ,
    JUMPING_FORWARD_JAZZ,
    FALLING_FORWARD_JAZZ,
    SHOOTING_WHILE_FALLING_JAZZ,
    STOP_SHOOTING_WHILE_FALLING_JAZZ,
    SHOOTING_JAZZ,
    STOP_SHOOTING_JAZZ,
    LOOKING_UP_JAZZ,
    SHOOTING_UP_JAZZ,
    CROUCHING_JAZZ, // 20
    CROUCH_JAZZ,
    CROUCH_SHOOTING_JAZZ,
    STANDING_UP_JAZZ,
    TRANSITION_TO_UPPERCUT_JAZZ,
    UPPERCUT_JAZZ,
    TRANSITION_TO_FALLING_AFTER_UPPERCUT_JAZZ,
    INTOXICATED_IDLE_JAZZ,
    INTOXICATED_WALKING_JAZZ,
    RECEIVE_DAMAGE_JAZZ,
    IMPACT_JAZZ, // 30
    DYING_JAZZ,
    IDLE_LORI,
    SHOOTING_FORWARD_LORI,
    STOP_SHOOTING_FORWARD_LORI,
    LOOKING_UP_LORI,
    SHOOTING_UP_LORI,
    CROUCHING_LORI,
    CROUCH_LORI,
    CROUCH_SHOOTING_LORI,
    STANDING_UP_LORI, // 40
    FLYING_KICK_LORI,
    WALKING_LORI,
    RUNNING_LORI,
    PREPARING_TO_DASH_LORI,
    DASHING_LORI,
    SKIDDING_LORI,
    STOP_SKIDDING_LORI,
    TRANSITION_TO_JUMPING_LORI,
    JUMPING_UP_LORI,
    TRANSITION_TO_FALLING_LORI, // 50
    FALLING_LORI,
    JUMPING_FORWARD_LORI,
    FALLING_FORWARD_LORI,
    SHOOTING_WHILE_FALLING_LORI,
    STOP_SHOOTING_WHILE_FALLING_LORI,
    LANDING_LORI,
    INTOXICATED_IDLE_LORI,
    INTOXICATED_WALKING_LORI,
    RECEIVE_DAMAGE_LORI,
    WALKING_LIZARD, // 60
    FLYING_BAT,
    WALKING_SKELETON,
    CRAB,
    FISH,
    TURTLE,
    GEM,
    COIN,
    FIREBALL,
    SHOT_FIREBALL,
    RED_ROCKET, // 70
    SHOT_RED_ROCKET,
    BULLET,
    BEACH_FLOOR,
    BEACH_FLOATING_FLOOR,
    BEACH_PLATFORM,
    BEACH_FLOATING_PLATFORM,
    BEACH_RISE,
    BEACH_DESCENT,
    BEACH_RISE_DESCENT,
    BEACH_EXIT_SIGN, // 80
    SPAWN_POINT,
    BEACH_LANDSCAPE,
    STATIC_ANIMATION,

    // Escenario
    Background_AIW,
    Background2,
    Background_BEACH,
    EMPTY_BACKGROUND,

    // entites
    JAZZ,
    LORI,
    SPAZ,

    BEACH_ALGAE,

    IDLE_SPAZ,
    SHOOTING_FORWARD_SPAZ,
    STOP_SHOOTING_FORWARD_SPAZ,
    LOOKING_UP_SPAZ,
    SHOOTING_UP_SPAZ,
    CROUCHING_SPAZ,
    CROUCH_SPAZ,
    CROUCH_SHOOTING_SPAZ,
    STANDING_UP_SPAZ,
    TRANSITION_TO_FLYING_KICK_SPAZ,
    FLYING_KICK_SPAZ,
    TRANSITION_AFTER_KICK_SPAZ,
    WALKING_SPAZ,
    RUNNING_SPAZ,
    PREPARING_TO_DASH_SPAZ,
    DASHING_SPAZ,
    SKIDDING_SPAZ,
    STOP_SKIDDING_SPAZ,
    TRANSITION_TO_JUMPING_SPAZ,
    JUMPING_UP_SPAZ,
    TRANSITION_TO_FALLING_SPAZ,
    FALLING_SPAZ,
    JUMPING_FORWARD_SPAZ,
    FALLING_FORWARD_SPAZ,
    SHOOTING_WHILE_FALLING_SPAZ,
    STOP_SHOOTING_WHILE_FALLING_SPAZ,
    LANDING_SPAZ,
    INTOXICATED_IDLE_SPAZ,
    INTOXICATED_WALKING_SPAZ,
    RECEIVE_DAMAGE_SPAZ,

    DYING_INVISIBLE, // meta

    // AIW
    ARROW,
    FLOOR_AIW,
    GUITAR,
    CHESIRE,
    DESCENT,
    RISE,
    RED_MUSHROOM,
    EXIT,
    ROCKS,

    BULLET_SOUND,
    RED_ROCKET_SOUND,
    FIREBALL_SOUND,
    COIN_SOUND,
    FLOOR2_AIW,
    ROCKS2_AIW,
    FLOOR3_AIW,
    STONE_TOWER,
    COLUMN_STONES,
    COLUMN_STONES_RIGHT,
    FLOOR4_AIW,
    ROCKS3_AIW,
    COLUMN_STONES_LOWER,
    COLUMN_STONES_LOWER_RIGHT,
    FLOOR_AFTER_RAISE,
    ROCKS_AFTER_RAISE,
    FLOOR_BEFORE_DESCENT,
    ROCKS_BEFORE_DESCENT,

    HURT_SOUND,
    DYING_SOUND,
    LANDING_SOUND,

    FLOOR_STONE_TOWER,
    MAD_HATTER,
    SKELETON,
    DYING_LORI,
    DYING_SPAZ,

    DYING_ENEMY_SOUND,
    POISON_FRUIT,
    POISONED_SOUND,

};

/*enum EntityType : uint8_t
{
    //JAZZ = 0x00,
    LORI,
    SPAZ,
    LIZARD,
    RAT,
};*/

enum Background : uint8_t
{
    INIT_SCREEN = 0X00,
    MAIN_SCREEN,
    BLACK_SCREEN,
    GENERAL_SCREEN,
};

enum Guns : uint8_t
{
    GREEN_GUN = 0X00,
    VIOLET_GUN,
    BLUE_GUN
};

#endif // LAST_ENUMS_H
